export const userRole = [
    { index: 'normal', value: '普通用户' },
    { index: 'editor', value: '测试维护' },
    { index: 'admin', value: '管理员' },
]

export const testLevel = [
    { index: 1, value: 'A级' },
    { index: 2, value: 'B级 +' },
    { index: 3, value: 'C级 +' },
    { index: 4, value: 'D级 +' },
];

export const hour = [
    { index: '00', value: '00' },
    { index: '01', value: '01' },
    { index: '02', value: '02' },
    { index: '03', value: '03' },
    { index: '04', value: '04' },
    { index: '05', value: '05' },
    { index: '06', value: '06' },
    { index: '07', value: '07' },
    { index: '08', value: '08' },
    { index: '09', value: '09' },
    { index: '10', value: '10' },
    { index: '11', value: '11' },
    { index: '12', value: '12' },
    { index: '13', value: '13' },
    { index: '14', value: '14' },
    { index: '15', value: '15' },
    { index: '16', value: '16' },
    { index: '17', value: '17' },
    { index: '18', value: '18' },
    { index: '19', value: '19' },
    { index: '20', value: '20' },
    { index: '21', value: '21' },
    { index: '22', value: '22' },
    { index: '23', value: '23' },
];

export const minute = [
    { index: '00', value: '00' },
    { index: '01', value: '01' },
    { index: '02', value: '02' },
    { index: '03', value: '03' },
    { index: '04', value: '04' },
    { index: '05', value: '05' },
    { index: '06', value: '06' },
    { index: '07', value: '07' },
    { index: '08', value: '08' },
    { index: '09', value: '09' },
    { index: '10', value: '10' },
    { index: '11', value: '11' },
    { index: '12', value: '12' },
    { index: '13', value: '13' },
    { index: '14', value: '14' },
    { index: '15', value: '15' },
    { index: '16', value: '16' },
    { index: '17', value: '17' },
    { index: '18', value: '18' },
    { index: '19', value: '19' },
    { index: '20', value: '20' },
    { index: '21', value: '21' },
    { index: '22', value: '22' },
    { index: '23', value: '23' },
    { index: '24', value: '24' },
    { index: '25', value: '25' },
    { index: '26', value: '26' },
    { index: '27', value: '27' },
    { index: '28', value: '28' },
    { index: '29', value: '29' },
    { index: '30', value: '30' },
    { index: '31', value: '31' },
    { index: '32', value: '32' },
    { index: '33', value: '33' },
    { index: '34', value: '34' },
    { index: '35', value: '35' },
    { index: '36', value: '36' },
    { index: '37', value: '37' },
    { index: '38', value: '38' },
    { index: '39', value: '39' },
    { index: '40', value: '40' },
    { index: '41', value: '41' },
    { index: '42', value: '42' },
    { index: '43', value: '43' },
    { index: '44', value: '44' },
    { index: '45', value: '45' },
    { index: '46', value: '46' },
    { index: '47', value: '47' },
    { index: '48', value: '48' },
    { index: '49', value: '49' },
    { index: '50', value: '50' },
    { index: '51', value: '51' },
    { index: '52', value: '52' },
    { index: '53', value: '53' },
    { index: '54', value: '54' },
    { index: '55', value: '55' },
    { index: '56', value: '56' },
    { index: '57', value: '57' },
    { index: '58', value: '58' },
    { index: '59', value: '59' },
];

export const requestMethod = [
    { index: 'GET', value: 'GET' },
    { index: 'POST', value: 'POST' },
    { index: 'PUT', value: 'PUT' },
    { index: 'DELETE', value: 'DELETE' },
];

export const requestContentType = [
    { index: 'application/x-www-form-urlencoded', value: 'application/x-www-form-urlencoded' },
    { index: 'application/json', value: 'application/json' },
    { index: 'application/xml', value: 'application/xml' },
    { index: 'application/javascript', value: 'application/javascript' },
    { index: 'multipart/form-data', value: 'multipart/form-data' },
    { index: 'text/plain', value: 'text/plain' },
    { index: 'text/xml', value: 'text/xml' },
    { index: 'text/html', value: 'text/html' },
];

export const paramSet = [
    { index: 'param', value: '参数' },
    { index: 'data', value: '数据源' },
]

export const dataSource = [
    { index: 'mysql', value: 'mysql' },
    { index: 'mysql_mysqli', value: 'mysql (mysqli)' },
    { index: 'mysql_pdo', value: 'mysql (pdo)' },
    { index: 'sqlsrv', value: 'sqlsrv' },
    { index: 'sqlsrv_pdo', value: 'sqlsrv (pdo)' },
    { index: 'oracle_oci', value: 'oracle (oci)' },
    { index: 'mongo', value: 'mongo' },
]

export const logSource = [
    { index: 'all', value: '全部' },
    { index: 'user', value: '用户' },
    { index: 'app', value: '应用' },
]